[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "relocation-model=pic",
    "-C", "link-arg=-pie",
    "-C", "link-arg=--no-dynamic-linker",
    "-C", "link-arg=--no-undefined",
    "-C", "link-arg=--build-id=none",
    "-C", "link-arg=--hash-style=sysv",
    "-C", "link-arg=-Tpie.ld",
]
