//! Phase-9 reusable, standalone no_std bitmap toolkit.
//!
//! All graphics operations use caller-owned slices and checked geometry;
//! neither a framebuffer address nor a kernel/device cap exists here. An
//! 800x600 scanout and a 320x200 client surface share the same routines.
//! `Canvas` cannot index outside its borrowed backing even for malicious
//! rectangles, negative coordinates, overflow-sized dimensions or text.
#![no_std]

pub const MAX_WIDTH: usize = 1024;
pub const MAX_HEIGHT: usize = 768;
pub const MAX_TEXT_BYTES: usize = 96;

/// Arena Sans 13, the proportional face (Phase 11.7). Generated by
/// tools/gen_face13.py; kept byte-for-byte as generated.
#[rustfmt::skip]
pub mod face13;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DrawError {
    InvalidGeometry,
    InvalidText,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Rect {
    pub x: i32,
    pub y: i32,
    pub width: u32,
    pub height: u32,
}

/// Opaque XRGB pixels; `stride` is in 32-bit pixels, not bytes.
/// A canvas borrows the complete span so there can be no alias with a
/// second mutable renderer in the same process.
pub struct Canvas<'a> {
    pixels: &'a mut [u32],
    width: usize,
    height: usize,
    stride: usize,
    /// Half-open pixel clip `[x0, x1) x [y0, y1)`, always inside the canvas.
    /// Every drawing operation is intersected with it; it defaults to the
    /// whole canvas, so callers that never set it see unchanged behaviour.
    clip: (usize, usize, usize, usize),
    /// Translation added to every coordinate a caller passes (scroll views,
    /// nested panels). Zero unless set, so existing callers are unchanged.
    origin: (i32, i32),
}

/// Blend `color` over `dst` with coverage `alpha` (0..=255), per channel.
pub fn blend(dst: u32, color: u32, alpha: u8) -> u32 {
    let a = u32::from(alpha);
    let mut out = 0;
    for shift in [0, 8, 16] {
        let d = (dst >> shift) & 0xff;
        let c = (color >> shift) & 0xff;
        out |= ((c * a + d * (255 - a) + 127) / 255) << shift;
    }
    out
}

/// Inked width of `text` in Arena Sans 13 (1 px between glyphs; bold adds
/// one column per glyph). Unknown characters measure as `?`.
pub fn measure13(text: &str, bold: bool) -> i32 {
    let mut w = 0i32;
    for (i, c) in text.chars().enumerate() {
        let g = face13::glyph(c).or_else(|| face13::glyph('?'));
        let gw = g.map_or(0, |g| i32::from(g.width)) + i32::from(bold);
        w += gw + i32::from(i != 0);
    }
    w
}

impl<'a> Canvas<'a> {
    pub fn new(
        pixels: &'a mut [u32],
        width: usize,
        height: usize,
        stride: usize,
    ) -> Result<Self, DrawError> {
        if width == 0
            || height == 0
            || width > MAX_WIDTH
            || height > MAX_HEIGHT
            || stride < width
            || stride > MAX_WIDTH
            || stride
                .checked_mul(height)
                .is_none_or(|size| size > pixels.len())
        {
            return Err(DrawError::InvalidGeometry);
        }
        Ok(Self {
            pixels,
            width,
            height,
            stride,
            clip: (0, 0, width, height),
            origin: (0, 0),
        })
    }

    /// Translate every later coordinate by (`x`, `y`) (absolute, not
    /// cumulative). The clip is unaffected: it stays in canvas pixels.
    pub fn set_origin(&mut self, x: i32, y: i32) {
        self.origin = (x, y);
    }

    pub fn origin(&self) -> (i32, i32) {
        self.origin
    }

    fn at(&self, x: i32, y: i32) -> (i64, i64) {
        (
            i64::from(x) + i64::from(self.origin.0),
            i64::from(y) + i64::from(self.origin.1),
        )
    }

    /// The part of `rect` (caller coordinates) inside the clip, in canvas
    /// pixels: `(x0, y0, x1, y1)`, possibly empty.
    fn span(&self, rect: Rect) -> (usize, usize, usize, usize) {
        let (cx0, cy0, cx1, cy1) = self.clip;
        let (x, y) = self.at(rect.x, rect.y);
        let x0 = x.clamp(cx0 as i64, cx1 as i64) as usize;
        let y0 = y.clamp(cy0 as i64, cy1 as i64) as usize;
        let x1 = (x + i64::from(rect.width)).clamp(x0 as i64, cx1 as i64) as usize;
        let y1 = (y + i64::from(rect.height)).clamp(y0 as i64, cy1 as i64) as usize;
        (x0, y0, x1, y1)
    }

    /// Blend `color` with coverage `alpha` over the opaque pixels of
    /// `rect` (selection washes, scrims, hover tints). Returns pixels touched.
    pub fn blend_rect(&mut self, rect: Rect, color: u32, alpha: u8) -> usize {
        let (x0, y0, x1, y1) = self.span(rect);
        for y in y0..y1 {
            for p in &mut self.pixels[y * self.stride + x0..y * self.stride + x1] {
                *p = blend(*p, color, alpha);
            }
        }
        (x1 - x0) * (y1 - y0)
    }

    /// Darken `rect` by `amount` (0..=255 toward black): shadows, pressed.
    pub fn darken_rect(&mut self, rect: Rect, amount: u8) -> usize {
        self.blend_rect(rect, 0, amount)
    }

    /// An 8-bit coverage mask (`width` x `height`, row `stride` bytes)
    /// blended in `color` at (`x`, `y`): soft shadows, smooth icons.
    pub fn mask_blit(
        &mut self,
        mask: &[u8],
        width: usize,
        height: usize,
        stride: usize,
        x: i32,
        y: i32,
        color: u32,
    ) -> Result<usize, DrawError> {
        if width == 0
            || height == 0
            || width > MAX_WIDTH
            || height > MAX_HEIGHT
            || stride < width
            || stride
                .checked_mul(height - 1)
                .and_then(|s| s.checked_add(width))
                .is_none_or(|span| span > mask.len())
        {
            return Err(DrawError::InvalidGeometry);
        }
        let (x0, y0, x1, y1) = self.span(Rect {
            x,
            y,
            width: width as u32,
            height: height as u32,
        });
        let (ox, oy) = self.at(x, y);
        let mut touched = 0;
        for dy in y0..y1 {
            let row = (dy as i64 - oy) as usize * stride;
            for dx in x0..x1 {
                let a = mask[row + (dx as i64 - ox) as usize];
                if a != 0 {
                    let p = &mut self.pixels[dy * self.stride + dx];
                    *p = blend(*p, color, a);
                    touched += 1;
                }
            }
        }
        Ok(touched)
    }

    /// A 1-bit mask (bit `i` of `rows[r]` = column `i`, at most 16 wide)
    /// in `color` at (`x`, `y`): icons and glyph rows as whole spans.
    pub fn bits_blit(&mut self, rows: &[u16], width: usize, x: i32, y: i32, color: u32) -> usize {
        let (ox, oy) = self.at(x, y);
        self.bits_at(rows, width, ox, oy, color)
    }

    /// `bits_blit` at absolute canvas coordinates (i64: never overflows).
    fn bits_at(&mut self, rows: &[u16], width: usize, ox: i64, oy: i64, color: u32) -> usize {
        if width == 0 || width > 16 {
            return 0;
        }
        let (cx0, cy0, cx1, cy1) = self.clip;
        let color = color & 0x00ff_ffff;
        let mut touched = 0;
        for (r, bits) in rows.iter().enumerate() {
            let py = oy + r as i64;
            if py < cy0 as i64 || py >= cy1 as i64 || *bits == 0 {
                continue;
            }
            let line = py as usize * self.stride;
            for i in 0..width {
                let px = ox + i as i64;
                if bits >> i & 1 == 1 && px >= cx0 as i64 && px < cx1 as i64 {
                    self.pixels[line + px as usize] = color;
                    touched += 1;
                }
            }
        }
        touched
    }

    /// Text in Arena Sans 13 with its top at `y`; returns the inked width.
    /// Bold double-strikes one column to the right. Characters the face
    /// lacks draw as `?`; overlong input is a typed refusal before any
    /// pixel changes.
    pub fn text13(
        &mut self,
        x: i32,
        y: i32,
        text: &str,
        color: u32,
        bold: bool,
    ) -> Result<i32, DrawError> {
        if text.chars().count() > 4 * MAX_TEXT_BYTES {
            return Err(DrawError::InvalidText);
        }
        // Pen and coordinates in i64: hostile x/y/origin never overflow.
        let (ox, oy) = self.at(x, y);
        let mut pen = 0i64;
        for (i, c) in text.chars().enumerate() {
            if i != 0 {
                pen += 1;
            }
            let Some(g) = face13::glyph(c).or_else(|| face13::glyph('?')) else {
                continue;
            };
            let w = usize::from(g.width);
            // Whole glyphs outside the clip cost nothing.
            let gx = ox + pen;
            if gx < self.clip.2 as i64 && gx + w as i64 + 1 > self.clip.0 as i64 {
                self.bits_at(&g.rows, w, gx, oy, color);
                if bold {
                    self.bits_at(&g.rows, w, gx + 1, oy, color);
                }
            }
            pen += i64::from(g.width) + i64::from(bold);
        }
        Ok(pen as i32)
    }

    /// Restrict all later drawing to `rect` intersected with the canvas.
    /// Damage-driven compositors use this to recompose only changed areas.
    pub fn set_clip(&mut self, rect: Rect) {
        let x0 = i64::from(rect.x).clamp(0, self.width as i64) as usize;
        let y0 = i64::from(rect.y).clamp(0, self.height as i64) as usize;
        let x1 = (i64::from(rect.x) + i64::from(rect.width)).clamp(0, self.width as i64) as usize;
        let y1 = (i64::from(rect.y) + i64::from(rect.height)).clamp(0, self.height as i64) as usize;
        self.clip = (x0, y0, x1.max(x0), y1.max(y0));
    }

    pub fn reset_clip(&mut self) {
        self.clip = (0, 0, self.width, self.height);
    }

    pub fn clip(&self) -> Rect {
        let (x0, y0, x1, y1) = self.clip;
        Rect {
            x: x0 as i32,
            y: y0 as i32,
            width: (x1 - x0) as u32,
            height: (y1 - y0) as u32,
        }
    }

    pub fn size(&self) -> (usize, usize) {
        (self.width, self.height)
    }

    /// Fill the current clip (the whole canvas unless a clip is set).
    pub fn clear(&mut self, color: u32) {
        let (x0, y0, x1, y1) = self.clip;
        let color = color & 0x00ff_ffff;
        for y in y0..y1 {
            self.pixels[y * self.stride + x0..y * self.stride + x1].fill(color);
        }
    }

    /// Rectangles are intersected with the canvas, never rejected merely
    /// for being partly offscreen. i64 math cannot overflow on i32+u32.
    /// Return the number of pixels actually touched for structural tests.
    pub fn fill_rect(&mut self, rect: Rect, color: u32) -> usize {
        let (x0, y0, x1, y1) = self.span(rect);
        let color = color & 0x00ff_ffff;
        for y in y0..y1 {
            self.pixels[y * self.stride + x0..y * self.stride + x1].fill(color);
        }
        (x1 - x0) * (y1 - y0)
    }

    /// This bitmap font is intentionally small and wholly owned here: each
    /// glyph is seven 5-bit rows, width 5, height 7, fixed advance 6. An
    /// unsupported printable glyph renders '?'; non-ASCII or oversized
    /// input is a typed refusal *before* any pixel is changed.
    pub fn text(&mut self, x: i32, y: i32, text: &str, color: u32) -> Result<usize, DrawError> {
        self.text_scaled(x, y, text, color, 1)
    }
    /// Owned bitmap glyphs at bounded integer scale, preserving case.
    /// Invalid scale or text refuses before changing any destination pixel.
    pub fn text_scaled(
        &mut self,
        x: i32,
        y: i32,
        text: &str,
        color: u32,
        scale: u8,
    ) -> Result<usize, DrawError> {
        if !(1..=3).contains(&scale)
            || text.len() > MAX_TEXT_BYTES
            || !text.bytes().all(|c| c.is_ascii_graphic() || c == b' ')
        {
            return Err(DrawError::InvalidText);
        }
        let mut touched = 0usize;
        let color = color & 0x00ff_ffff;
        let (cx0, cy0, cx1, cy1) = (
            self.clip.0 as i64,
            self.clip.1 as i64,
            self.clip.2 as i64,
            self.clip.3 as i64,
        );
        let (x, y) = (
            x.saturating_add(self.origin.0),
            y.saturating_add(self.origin.1),
        );
        for (i, c) in text.bytes().enumerate() {
            let gx = i64::from(x) + (i as i64) * 6 * i64::from(scale);
            // Whole glyph cells outside the clip cost nothing.
            if gx >= cx1 || gx + 5 * i64::from(scale) <= cx0 {
                continue;
            }
            let bitmap = font::glyph(c);
            for (row, bits) in bitmap.iter().enumerate() {
                let py = i64::from(y) + row as i64 * i64::from(scale);
                if py + i64::from(scale) <= cy0 || py >= cy1 {
                    continue;
                }
                for column in 0..5 {
                    let px = gx + column * i64::from(scale);
                    if px + i64::from(scale) <= cx0
                        || px >= cx1
                        || (bits & (1 << (4 - column))) == 0
                    {
                        continue;
                    }
                    for dy in 0..i64::from(scale) {
                        for dx in 0..i64::from(scale) {
                            let (xx, yy) = (px + dx, py + dy);
                            if xx >= cx0 && yy >= cy0 && xx < cx1 && yy < cy1 {
                                self.pixels[yy as usize * self.stride + xx as usize] = color;
                                touched += 1;
                            }
                        }
                    }
                }
            }
        }
        Ok(touched)
    }

    /// Opaque, clipped z-order composition. The source is a *different*
    /// immutable slice and validated width/stride; the compositor decides
    /// who owns it, not this deliberately authority-free helper.
    pub fn blit(
        &mut self,
        source: &[u32],
        src_width: usize,
        src_height: usize,
        src_stride: usize,
        x: i32,
        y: i32,
    ) -> Result<usize, DrawError> {
        if src_width == 0
            || src_height == 0
            || src_width > MAX_WIDTH
            || src_height > MAX_HEIGHT
            || src_stride < src_width
            || src_stride > MAX_WIDTH
            || src_stride
                .checked_mul(src_height)
                .is_none_or(|span| span > source.len())
        {
            return Err(DrawError::InvalidGeometry);
        }
        let (x0, y0, x1, y1) = self.span(Rect {
            x,
            y,
            width: src_width as u32,
            height: src_height as u32,
        });
        let (x, y) = self.at(x, y);
        let sx0 = (x0 as i64 - x) as usize;
        for dy in y0..y1 {
            let sy = (dy as i64 - y) as usize;
            let src = &source[sy * src_stride + sx0..sy * src_stride + sx0 + (x1 - x0)];
            let dst = &mut self.pixels[dy * self.stride + x0..dy * self.stride + x1];
            for (d, s) in dst.iter_mut().zip(src) {
                *d = *s & 0x00ff_ffff;
            }
        }
        Ok((x1 - x0) * (y1 - y0))
    }
}

/// Owned 5x7 ASCII subset. No firmware font, external TTF, allocations,
/// graphics server policy or host font library is linked into ring 3.
mod font {
    pub fn glyph(c: u8) -> [u8; 7] {
        let lower = match c {
            b'a' => Some([0, 0, 14, 1, 15, 17, 15]),
            b'b' => Some([16, 16, 30, 17, 17, 17, 30]),
            b'c' => Some([0, 0, 14, 17, 16, 17, 14]),
            b'd' => Some([1, 1, 15, 17, 17, 17, 15]),
            b'e' => Some([0, 0, 14, 17, 31, 16, 14]),
            b'f' => Some([6, 8, 8, 28, 8, 8, 8]),
            b'g' => Some([0, 0, 15, 17, 15, 1, 14]),
            b'h' => Some([16, 16, 30, 17, 17, 17, 17]),
            b'i' => Some([4, 0, 12, 4, 4, 4, 14]),
            b'j' => Some([2, 0, 6, 2, 2, 18, 12]),
            b'k' => Some([16, 16, 18, 20, 24, 20, 18]),
            b'l' => Some([12, 4, 4, 4, 4, 4, 14]),
            b'm' => Some([0, 0, 26, 21, 21, 21, 21]),
            b'n' => Some([0, 0, 30, 17, 17, 17, 17]),
            b'o' => Some([0, 0, 14, 17, 17, 17, 14]),
            b'p' => Some([0, 0, 30, 17, 30, 16, 16]),
            b'q' => Some([0, 0, 15, 17, 15, 1, 1]),
            b'r' => Some([0, 0, 22, 25, 16, 16, 16]),
            b's' => Some([0, 0, 15, 16, 14, 1, 30]),
            b't' => Some([8, 8, 28, 8, 8, 9, 6]),
            b'u' => Some([0, 0, 17, 17, 17, 19, 13]),
            b'v' => Some([0, 0, 17, 17, 17, 10, 4]),
            b'w' => Some([0, 0, 17, 17, 21, 21, 10]),
            b'x' => Some([0, 0, 17, 10, 4, 10, 17]),
            b'y' => Some([0, 0, 17, 17, 15, 1, 14]),
            b'z' => Some([0, 0, 31, 2, 4, 8, 31]),
            _ => None,
        };
        if let Some(rows) = lower {
            return rows;
        }
        match c.to_ascii_uppercase() {
            b'A' => [14, 17, 17, 31, 17, 17, 17],
            b'B' => [30, 17, 17, 30, 17, 17, 30],
            b'C' => [14, 17, 16, 16, 16, 17, 14],
            b'D' => [30, 17, 17, 17, 17, 17, 30],
            b'E' => [31, 16, 16, 30, 16, 16, 31],
            b'F' => [31, 16, 16, 30, 16, 16, 16],
            b'G' => [14, 17, 16, 23, 17, 17, 15],
            b'H' => [17, 17, 17, 31, 17, 17, 17],
            b'I' => [31, 4, 4, 4, 4, 4, 31],
            b'J' => [7, 2, 2, 2, 18, 18, 12],
            b'K' => [17, 18, 20, 24, 20, 18, 17],
            b'L' => [16, 16, 16, 16, 16, 16, 31],
            b'M' => [17, 27, 21, 21, 17, 17, 17],
            b'N' => [17, 25, 21, 19, 17, 17, 17],
            b'O' => [14, 17, 17, 17, 17, 17, 14],
            b'P' => [30, 17, 17, 30, 16, 16, 16],
            b'Q' => [14, 17, 17, 17, 21, 18, 13],
            b'R' => [30, 17, 17, 30, 20, 18, 17],
            b'S' => [15, 16, 16, 14, 1, 1, 30],
            b'T' => [31, 4, 4, 4, 4, 4, 4],
            b'U' => [17, 17, 17, 17, 17, 17, 14],
            b'V' => [17, 17, 17, 17, 17, 10, 4],
            b'W' => [17, 17, 17, 21, 21, 21, 10],
            b'X' => [17, 17, 10, 4, 10, 17, 17],
            b'Y' => [17, 17, 10, 4, 4, 4, 4],
            b'Z' => [31, 1, 2, 4, 8, 16, 31],
            b'0' => [14, 17, 19, 21, 25, 17, 14],
            b'1' => [4, 12, 4, 4, 4, 4, 14],
            b'2' => [14, 17, 1, 2, 4, 8, 31],
            b'3' => [30, 1, 1, 14, 1, 1, 30],
            b'4' => [2, 6, 10, 18, 31, 2, 2],
            b'5' => [31, 16, 16, 30, 1, 1, 30],
            b'6' => [14, 16, 16, 30, 17, 17, 14],
            b'7' => [31, 1, 2, 4, 8, 8, 8],
            b'8' => [14, 17, 17, 14, 17, 17, 14],
            b'9' => [14, 17, 17, 15, 1, 1, 14],
            b' ' => [0; 7],
            b'.' => [0, 0, 0, 0, 0, 12, 12],
            b':' => [0, 12, 12, 0, 12, 12, 0],
            b',' => [0, 0, 0, 0, 12, 12, 8],
            b'-' => [0, 0, 0, 31, 0, 0, 0],
            b'+' => [0, 4, 4, 31, 4, 4, 0],
            b'/' => [1, 1, 2, 4, 8, 16, 16],
            b'!' => [4, 4, 4, 4, 4, 0, 4],
            b'?' => [14, 17, 1, 2, 4, 0, 4],
            b'(' => [2, 4, 8, 8, 8, 4, 2],
            b')' => [8, 4, 2, 2, 2, 4, 8],
            b'[' => [14, 8, 8, 8, 8, 8, 14],
            b']' => [14, 2, 2, 2, 2, 2, 14],
            b'=' => [0, 0, 31, 0, 31, 0, 0],
            b'_' => [0, 0, 0, 0, 0, 0, 31],
            b'>' => [16, 8, 4, 2, 4, 8, 16],
            b'<' => [1, 2, 4, 8, 4, 2, 1],
            b'|' => [4, 4, 4, 4, 4, 4, 4],
            b'%' => [25, 25, 2, 4, 8, 19, 19],
            b'*' => [0, 21, 14, 31, 14, 21, 0],
            b'#' => [10, 31, 10, 10, 31, 10, 0],
            b'&' => [12, 18, 20, 8, 21, 18, 13],
            b'@' => [14, 17, 23, 21, 23, 16, 14],
            b'$' => [4, 15, 20, 14, 5, 30, 4],
            b'^' => [4, 10, 17, 0, 0, 0, 0],
            b'~' => [0, 0, 9, 22, 0, 0, 0],
            b'`' => [8, 4, 0, 0, 0, 0, 0],
            b'\'' => [4, 4, 0, 0, 0, 0, 0],
            b'"' => [10, 10, 0, 0, 0, 0, 0],
            b'\\' => [16, 16, 8, 4, 2, 1, 1],
            b'{' => [2, 4, 4, 8, 4, 4, 2],
            b'}' => [8, 4, 4, 2, 4, 4, 8],
            b';' => [0, 12, 12, 0, 12, 12, 8],
            _ => [14, 17, 1, 2, 4, 0, 4], // conspicuous replacement
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn checked_geometry_and_disjoint_padding() {
        let mut pixels = [0xdead_beefu32; 4 * 3];
        assert!(Canvas::new(&mut pixels, 5, 3, 4).is_err());
        let mut c = Canvas::new(&mut pixels, 3, 3, 4).unwrap();
        c.clear(0xff34_5678);
        assert_eq!(
            c.fill_rect(
                Rect {
                    x: -1,
                    y: -1,
                    width: 2,
                    height: 2
                },
                0x00abcdef
            ),
            1
        );
        assert_eq!(
            c.fill_rect(
                Rect {
                    x: i32::MAX,
                    y: i32::MAX,
                    width: u32::MAX,
                    height: u32::MAX
                },
                0
            ),
            0
        );
        assert_eq!(pixels[0], 0x00ab_cdef);
        assert_eq!([pixels[3], pixels[7], pixels[11]], [0xdead_beef; 3]);
    }

    #[test]
    fn owned_font_and_bounded_rejection() {
        let mut pixels = [0u32; 24 * 16];
        let mut c = Canvas::new(&mut pixels, 24, 16, 24).unwrap();
        assert!(c.text(1, 1, "A9!?", 0x00ffffff).unwrap() > 20);
        let mut before = [0u32; 24 * 16];
        before.copy_from_slice(c.pixels);
        assert_eq!(c.text(0, 0, "☃", 1), Err(DrawError::InvalidText));
        let long = [b'X'; MAX_TEXT_BYTES + 1];
        assert_eq!(
            c.text(0, 0, core::str::from_utf8(&long).unwrap(), 1),
            Err(DrawError::InvalidText)
        );
        assert_eq!(c.pixels, before);
        assert_eq!(c.text_scaled(0, 0, "A", 1, 0), Err(DrawError::InvalidText));
        assert_eq!(c.text_scaled(0, 0, "A", 1, 4), Err(DrawError::InvalidText));
        assert_eq!(c.pixels, before);
        assert!(c.text_scaled(-3, -2, "a", 1, 2).unwrap() > 20);
        assert_ne!(font::glyph(b'a'), font::glyph(b'A'));
        for c in b'a'..=b'z' {
            assert_ne!(font::glyph(c), font::glyph(c.to_ascii_uppercase()));
        }
        assert_ne!(font::glyph(b'A'), font::glyph(b'B'));
    }

    #[test]
    fn clipped_opaque_blit_and_refusals() {
        let mut dst = [0x123u32; 5 * 5];
        let src = [0xAABB_CCDDu32; 3 * 3];
        let mut c = Canvas::new(&mut dst, 5, 5, 5).unwrap();
        assert_eq!(c.blit(&src, 3, 3, 3, -1, -1), Ok(4));
        assert_eq!(c.pixels[0], 0x00bb_ccdd);
        assert_eq!(
            c.blit(&src, usize::MAX, 3, 3, 0, 0),
            Err(DrawError::InvalidGeometry)
        );
        assert_eq!(
            c.blit(&src, 3, 3, usize::MAX, 0, 0),
            Err(DrawError::InvalidGeometry)
        );
        assert_eq!(c.blit(&src, 3, 3, 3, i32::MAX, i32::MAX), Ok(0));
        assert_eq!(c.pixels[24], 0x123);
    }

    #[test]
    fn clip_restricts_every_operation_exactly() {
        // Drawing the same scene clipped must equal the unclipped scene
        // inside the clip and leave every pixel outside it untouched.
        fn scene(c: &mut Canvas<'_>) {
            c.clear(0x0011_2233);
            c.fill_rect(
                Rect {
                    x: 3,
                    y: 2,
                    width: 20,
                    height: 9,
                },
                0x00ff_0000,
            );
            let src = [0x00aa_bbccu32; 6 * 4];
            c.blit(&src, 6, 4, 6, 10, 5).unwrap();
            c.text_scaled(1, 8, "Ab9", 0x0000_ff00, 2).unwrap();
        }
        let (w, h) = (32usize, 24usize);
        let mut full = [0u32; 32 * 24];
        scene(&mut Canvas::new(&mut full, w, h, w).unwrap());
        let clip = Rect {
            x: 7,
            y: 4,
            width: 11,
            height: 13,
        };
        let mut part = [0xdead_beefu32; 32 * 24];
        let mut c = Canvas::new(&mut part, w, h, w).unwrap();
        c.set_clip(clip);
        assert_eq!(c.clip(), clip);
        scene(&mut c);
        for y in 0..h {
            for x in 0..w {
                let inside = (7..18).contains(&x) && (4..17).contains(&y);
                let expect = if inside { full[y * w + x] } else { 0xdead_beef };
                assert_eq!(part[y * w + x], expect, "({x},{y})");
            }
        }
        // Clip is intersected with the canvas; reset restores everything.
        let mut c = Canvas::new(&mut part, w, h, w).unwrap();
        c.set_clip(Rect {
            x: -5,
            y: 20,
            width: 100,
            height: 100,
        });
        assert_eq!(
            c.clip(),
            Rect {
                x: 0,
                y: 20,
                width: 32,
                height: 4
            }
        );
        c.set_clip(Rect {
            x: 40,
            y: 40,
            width: 4,
            height: 4,
        });
        assert_eq!(
            c.fill_rect(
                Rect {
                    x: 0,
                    y: 0,
                    width: 32,
                    height: 24
                },
                1
            ),
            0
        );
        c.reset_clip();
        assert_eq!(
            c.fill_rect(
                Rect {
                    x: 0,
                    y: 0,
                    width: 32,
                    height: 24
                },
                1
            ),
            32 * 24
        );
    }
    #[test]
    fn origin_translates_every_operation_exactly() {
        let src = [0x00aa_bbccu32; 4 * 3];
        let mask = [255u8, 128, 0, 64];
        let icon = [0b101u16, 0b010];
        let draw = |c: &mut Canvas<'_>, dx: i32, dy: i32| {
            c.fill_rect(
                Rect {
                    x: 2 + dx,
                    y: 1 + dy,
                    width: 5,
                    height: 4,
                },
                0x0010_2030,
            );
            c.blit(&src, 4, 3, 4, 6 + dx, 7 + dy).unwrap();
            c.text_scaled(1 + dx, 9 + dy, "Ab", 0x0000_ff00, 1).unwrap();
            c.text13(12 + dx, 2 + dy, "Hi, gy", 0x00ff_00ff, true)
                .unwrap();
            c.mask_blit(&mask, 2, 2, 2, 20 + dx, 12 + dy, 0x00ff_ffff)
                .unwrap();
            c.bits_blit(&icon, 3, 24 + dx, 14 + dy, 0x0000_00ff);
            c.blend_rect(
                Rect {
                    x: 3 + dx,
                    y: 3 + dy,
                    width: 10,
                    height: 10,
                },
                0x00ff_ff00,
                100,
            );
        };
        let mut a = [0x0011_1111u32; 40 * 24];
        let mut b = a;
        let mut ca = Canvas::new(&mut a, 40, 24, 40).unwrap();
        ca.set_clip(Rect {
            x: 4,
            y: 2,
            width: 30,
            height: 18,
        });
        draw(&mut ca, 5, 3);
        let mut cb = Canvas::new(&mut b, 40, 24, 40).unwrap();
        cb.set_clip(Rect {
            x: 4,
            y: 2,
            width: 30,
            height: 18,
        });
        cb.set_origin(5, 3);
        draw(&mut cb, 0, 0);
        assert_eq!(a, b);
        // Hostile coordinates with an origin never overflow or escape.
        let mut c = Canvas::new(&mut a, 40, 24, 40).unwrap();
        c.set_origin(i32::MAX, i32::MIN);
        c.text_scaled(i32::MAX, i32::MIN, "A", 1, 3).unwrap();
        c.text13(i32::MAX, i32::MAX, "A", 1, false).unwrap();
        assert_eq!(
            c.fill_rect(
                Rect {
                    x: i32::MAX,
                    y: 0,
                    width: u32::MAX,
                    height: 1
                },
                0
            ),
            0
        );
    }

    #[test]
    fn blend_mask_and_bits_are_exact_and_bounded() {
        assert_eq!(blend(0x0010_2030, 0x00f0_e0d0, 0), 0x0010_2030);
        assert_eq!(blend(0x0010_2030, 0x00f0_e0d0, 255), 0x00f0_e0d0);
        assert_eq!(blend(0, 0x00ff_ffff, 128), 0x0080_8080);
        let mut px = [0u32; 8 * 8];
        let mut c = Canvas::new(&mut px, 8, 8, 8).unwrap();
        let mask = [255u8; 9];
        assert_eq!(c.mask_blit(&mask, 3, 3, 3, -1, -1, 0x00ff_ffff), Ok(4));
        assert_eq!(
            c.mask_blit(&mask, 3, 4, 3, 0, 0, 1),
            Err(DrawError::InvalidGeometry)
        );
        assert_eq!(
            c.mask_blit(&mask, 4, 2, 3, 0, 0, 1),
            Err(DrawError::InvalidGeometry)
        );
        assert_eq!(c.bits_blit(&[0xffff], 17, 0, 0, 1), 0);
        assert_eq!(c.bits_blit(&[0b11], 2, 7, 7, 0x00ab_cdef), 1);
        assert_eq!(
            c.darken_rect(
                Rect {
                    x: 0,
                    y: 0,
                    width: 1,
                    height: 1
                },
                255
            ),
            1
        );
        assert_eq!(px[0], 0);
        assert_eq!(px[63], 0x00ab_cdef);
    }

    #[test]
    fn face13_is_complete_measured_and_clipped() {
        // Every glyph's ink lies inside its width and cell; the table is
        // sorted (binary search) and covers printable ASCII.
        for w in face13::GLYPHS.windows(2) {
            assert!(w[0].ch < w[1].ch);
        }
        for g in &face13::GLYPHS {
            assert!((1..=16).contains(&g.width));
            assert!(
                g.rows.iter().all(|r| u32::from(*r) < 1 << g.width),
                "{:?}",
                g.ch
            );
            assert_eq!((g.rows[0], g.rows[12]), (0, 0));
        }
        for c in (b' '..=b'~').map(char::from) {
            assert!(face13::glyph(c).is_some(), "{c:?}");
        }
        for c in [
            '\u{2018}', '\u{2019}', '\u{201c}', '\u{201d}', '\u{2013}', '\u{2014}', '\u{2026}',
        ] {
            assert!(face13::glyph(c).is_some());
        }
        // Case distinct; proportional (i narrower than m).
        for c in b'a'..=b'z' {
            let (l, u) = (char::from(c), char::from(c.to_ascii_uppercase()));
            assert_ne!(
                face13::glyph(l).unwrap().rows,
                face13::glyph(u).unwrap().rows
            );
        }
        assert!(measure13("i", false) < measure13("m", false));
        let mut px = [0u32; 120 * 16];
        let mut c = Canvas::new(&mut px, 120, 16, 120).unwrap();
        for (s, bold) in [
            ("Hello, World!", false),
            ("Documents \u{2014} 3 items", true),
            ("\u{263a}x", false),
        ] {
            assert_eq!(c.text13(0, 0, s, 1, bold).unwrap(), measure13(s, bold));
        }
        assert_eq!(measure13("\u{263a}", false), measure13("?", false));
        // Refusal before any pixel changes.
        let before = px;
        let mut c = Canvas::new(&mut px, 120, 16, 120).unwrap();
        let long = [b'x'; 4 * MAX_TEXT_BYTES + 1];
        let long = core::str::from_utf8(&long).unwrap();
        assert_eq!(c.text13(0, 0, long, 1, false), Err(DrawError::InvalidText));
        assert_eq!(px, before);
        // Clipped text equals unclipped text inside the clip, untouched outside.
        let mut full = [0u32; 60 * 16];
        let mut cf = Canvas::new(&mut full, 60, 16, 60).unwrap();
        cf.text13(-3, 1, "Quick fox, jumps", 0x00ff_ffff, false)
            .unwrap();
        let mut part = [0u32; 60 * 16];
        let mut cp = Canvas::new(&mut part, 60, 16, 60).unwrap();
        cp.set_clip(Rect {
            x: 10,
            y: 3,
            width: 30,
            height: 8,
        });
        cp.text13(-3, 1, "Quick fox, jumps", 0x00ff_ffff, false)
            .unwrap();
        for y in 0..16 {
            for x in 0..60 {
                let inside = (10..40).contains(&x) && (3..11).contains(&y);
                let want = if inside { full[y * 60 + x] } else { 0 };
                assert_eq!(part[y * 60 + x], want, "{x},{y}");
            }
        }
    }
}
