#!/usr/bin/env python3
"""Generate userspace/gfxkit/src/face13.rs from tools/face13.txt.

`--check` regenerates in memory and fails if the checked-in Rust differs
(the art file is the single source of truth for Arena Sans 13).
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ART = ROOT / 'tools/face13.txt'
OUT = ROOT / 'userspace/gfxkit/src/face13.rs'
HEIGHT = 13
ART_ROWS = 11


def parse():
    glyphs = {}
    current = None
    rows = []

    def close():
        if current is None:
            return
        if not rows:
            raise SystemExit(f'{current!r}: no rows')
        width = len(rows[0])
        if not 1 <= width <= 16 or any(len(r) != width for r in rows):
            raise SystemExit(f'{current!r}: inconsistent or invalid width')
        if len(rows) > ART_ROWS or any(set(r) - {'#', '.'} for r in rows):
            raise SystemExit(f'{current!r}: bad rows')
        if current in glyphs:
            raise SystemExit(f'{current!r}: duplicate')
        cell = [0] * HEIGHT
        for i, r in enumerate(rows):
            cell[i + 1] = sum(1 << x for x, ch in enumerate(r) if ch == '#')
        glyphs[current] = (width, cell)

    for line in ART.read_text().splitlines():
        if current is None and (line.startswith('#') or not line.strip()):
            continue
        if line.startswith('= '):
            close()
            name = line[2:]
            current = chr(int(name[2:], 16)) if name.startswith('U+') else name
            if len(current) != 1:
                raise SystemExit(f'bad glyph name {name!r}')
            rows = []
        elif line.strip():
            rows.append(line.strip())
    close()
    return glyphs


def render(glyphs):
    out = ['//! Arena Sans 13 (Phase 11.7): ArenaOS\'s own proportional bitmap face.',
           '//! Generated by tools/gen_face13.py from tools/face13.txt; do not edit.',
           '//! Rows are 13 pixels tall; bit x of a row is pixel column x.',
           '',
           'pub const HEIGHT: usize = 13;',
           '/// Rows above the baseline row (inclusive): text sits on row 9.',
           'pub const BASELINE: usize = 9;',
           '',
           '#[derive(Clone, Copy, Debug, PartialEq, Eq)]',
           'pub struct Glyph {',
           '    pub ch: char,',
           '    pub width: u8,',
           '    pub rows: [u16; HEIGHT],',
           '}',
           '',
           f'pub static GLYPHS: [Glyph; {len(glyphs)}] = [']
    for ch in sorted(glyphs):
        width, cell = glyphs[ch]
        rows = ', '.join(str(r) for r in cell)
        out.append(f'    Glyph {{ ch: {rust_char(ch)}, width: {width}, rows: [{rows}] }},')
    out += ['];', '',
            '/// The glyph for `c`, if the face has one.',
            'pub fn glyph(c: char) -> Option<&\'static Glyph> {',
            '    GLYPHS.binary_search_by(|g| g.ch.cmp(&c)).ok().map(|i| &GLYPHS[i])',
            '}', '']
    return '\n'.join(out)


def rust_char(ch):
    if ch == "'":
        return "'\\''"
    if ch == '\\':
        return "'\\\\'"
    if ord(ch) < 0x80:
        return f"'{ch}'"
    return f"'\\u{{{ord(ch):04x}}}'"


def generate():
    return render(parse())


def main():
    text = generate()
    if '--check' in sys.argv:
        if OUT.read_text() != text:
            raise SystemExit('face13.rs is stale: run tools/gen_face13.py')
        print(f'[face13] {OUT.relative_to(ROOT)} matches {ART.relative_to(ROOT)}')
        return
    OUT.write_text(text)
    print(f'[face13] wrote {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
